### PR TITLE
Adding extra 3.0 features 

### PR DESCRIPTION
**Pull request by glenrobson**
Added:
 * Up scaling
 * Removed size `full` and replaced with `max`

### CODE REVIEW

**Comment by glenrobson** [comment]
So to fix the travis checks it looks like I have to deploy a new version of the iiif-validator to pip

**Comment by glenrobson** [comment]
Now need to fix the formatting errors:

```
 '\n\n'

iiif/manipulator.py:310:13: E201 whitespace after '('

iiif/manipulator.py:310:16: E225 missing whitespace around operator

iiif/manipulator.py:310:32: E225 missing whitespace around operator

iiif/manipulator.py:311:15: E111 indentation is not a multiple of four

iiif/manipulator.py:311:39: E231 missing whitespace after ','

iiif/manipulator.py:312:22: E128 continuation line under-indented for visual indent

iiif/request.py:420:68: W291 trailing whitespace

iiif/request.py:423:38: W291 trailing whitespace

The command "pep8 --ignore=E501 *.py iiif/*.py iiif/generators/*.py tests/*.py tests/testlib/*.py" exited with 1.
```

**Comment by glenrobson** [comment]
I think this is ready for merging if your OK with it.

**Comment by zimeon** [comment]
Part of #38

**Pull request merged**
